// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: field_options.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "field_options.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
#include "Log.h"
// @@protoc_insertion_point(includes)

namespace Battlenet {

namespace {

const ::google::protobuf::EnumDescriptor* LogOption_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_field_5foptions_2eproto() {
  protobuf_AddDesc_field_5foptions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "field_options.proto");
  GOOGLE_CHECK(file != NULL);
  LogOption_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_field_5foptions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_field_5foptions_2eproto() {
}

void protobuf_AddDesc_field_5foptions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023field_options.proto\022\tBattlenet\032 google"
    "/protobuf/descriptor.proto* \n\tLogOption\022"
    "\n\n\006HIDDEN\020\001\022\007\n\003HEX\020\002:B\n\003log\022\035.google.pro"
    "tobuf.FieldOptions\030\320\206\003 \001(\0162\024.Battlenet.L"
    "ogOptionB\002H\001", 172);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "field_options.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterEnumExtension(
    &::google::protobuf::FieldOptions::default_instance(),
    50000, 14, false, false,
    &::Battlenet::LogOption_IsValid);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_field_5foptions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_field_5foptions_2eproto {
  StaticDescriptorInitializer_field_5foptions_2eproto() {
    protobuf_AddDesc_field_5foptions_2eproto();
  }
} static_descriptor_initializer_field_5foptions_2eproto_;
const ::google::protobuf::EnumDescriptor* LogOption_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LogOption_descriptor_;
}
bool LogOption_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::Battlenet::LogOption, ::Battlenet::LogOption_IsValid>, 14, false >
  log(kLogFieldNumber, static_cast< ::Battlenet::LogOption >(1));

// @@protoc_insertion_point(namespace_scope)

}  // namespace Battlenet

// @@protoc_insertion_point(global_scope)
