// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification_types.proto

#ifndef PROTOBUF_notification_5ftypes_2eproto__INCLUDED
#define PROTOBUF_notification_5ftypes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "account_types.pb.h"
#include "attribute_types.pb.h"
#include "entity_types.pb.h"
#include "rpc_types.pb.h"
// @@protoc_insertion_point(includes)

namespace Battlenet {
namespace notification {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_notification_5ftypes_2eproto();
void protobuf_AssignDesc_notification_5ftypes_2eproto();
void protobuf_ShutdownFile_notification_5ftypes_2eproto();

class Target;
class Subscription;
class Notification;

// ===================================================================

class Target : public ::google::protobuf::Message {
 public:
  Target();
  virtual ~Target();

  Target(const Target& from);

  inline Target& operator=(const Target& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Target& default_instance();

  void Swap(Target* other);

  // implements Message ----------------------------------------------

  Target* New() const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Battlenet.account.Identity identity = 1;
  inline bool has_identity() const;
  inline void clear_identity();
  static const int kIdentityFieldNumber = 1;
  inline const ::Battlenet::account::Identity& identity() const;
  inline ::Battlenet::account::Identity* mutable_identity();
  inline ::Battlenet::account::Identity* release_identity();
  inline void set_allocated_identity(::Battlenet::account::Identity* identity);

  // optional string type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline const ::std::string& type() const;
  inline void set_type(const ::std::string& value);
  inline void set_type(const char* value);
  inline void set_type(const char* value, size_t size);
  inline ::std::string* mutable_type();
  inline ::std::string* release_type();
  inline void set_allocated_type(::std::string* type);

  // @@protoc_insertion_point(class_scope:Battlenet.notification.Target)
 private:
  inline void set_has_identity();
  inline void clear_has_identity();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::Battlenet::account::Identity* identity_;
  ::std::string* type_;
  friend void  protobuf_AddDesc_notification_5ftypes_2eproto();
  friend void protobuf_AssignDesc_notification_5ftypes_2eproto();
  friend void protobuf_ShutdownFile_notification_5ftypes_2eproto();

  void InitAsDefaultInstance();
  static Target* default_instance_;
};
// -------------------------------------------------------------------

class Subscription : public ::google::protobuf::Message {
 public:
  Subscription();
  virtual ~Subscription();

  Subscription(const Subscription& from);

  inline Subscription& operator=(const Subscription& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Subscription& default_instance();

  void Swap(Subscription* other);

  // implements Message ----------------------------------------------

  Subscription* New() const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Battlenet.notification.Target target = 1;
  inline int target_size() const;
  inline void clear_target();
  static const int kTargetFieldNumber = 1;
  inline const ::Battlenet::notification::Target& target(int index) const;
  inline ::Battlenet::notification::Target* mutable_target(int index);
  inline ::Battlenet::notification::Target* add_target();
  inline const ::google::protobuf::RepeatedPtrField< ::Battlenet::notification::Target >&
      target() const;
  inline ::google::protobuf::RepeatedPtrField< ::Battlenet::notification::Target >*
      mutable_target();

  // optional .Battlenet.account.Identity subscriber = 2;
  inline bool has_subscriber() const;
  inline void clear_subscriber();
  static const int kSubscriberFieldNumber = 2;
  inline const ::Battlenet::account::Identity& subscriber() const;
  inline ::Battlenet::account::Identity* mutable_subscriber();
  inline ::Battlenet::account::Identity* release_subscriber();
  inline void set_allocated_subscriber(::Battlenet::account::Identity* subscriber);

  // optional bool delivery_required = 3 [default = false];
  inline bool has_delivery_required() const;
  inline void clear_delivery_required();
  static const int kDeliveryRequiredFieldNumber = 3;
  inline bool delivery_required() const;
  inline void set_delivery_required(bool value);

  // @@protoc_insertion_point(class_scope:Battlenet.notification.Subscription)
 private:
  inline void set_has_subscriber();
  inline void clear_has_subscriber();
  inline void set_has_delivery_required();
  inline void clear_has_delivery_required();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Battlenet::notification::Target > target_;
  ::Battlenet::account::Identity* subscriber_;
  bool delivery_required_;
  friend void  protobuf_AddDesc_notification_5ftypes_2eproto();
  friend void protobuf_AssignDesc_notification_5ftypes_2eproto();
  friend void protobuf_ShutdownFile_notification_5ftypes_2eproto();

  void InitAsDefaultInstance();
  static Subscription* default_instance_;
};
// -------------------------------------------------------------------

class Notification : public ::google::protobuf::Message {
 public:
  Notification();
  virtual ~Notification();

  Notification(const Notification& from);

  inline Notification& operator=(const Notification& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Notification& default_instance();

  void Swap(Notification* other);

  // implements Message ----------------------------------------------

  Notification* New() const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Battlenet.EntityId sender_id = 1;
  inline bool has_sender_id() const;
  inline void clear_sender_id();
  static const int kSenderIdFieldNumber = 1;
  inline const ::Battlenet::EntityId& sender_id() const;
  inline ::Battlenet::EntityId* mutable_sender_id();
  inline ::Battlenet::EntityId* release_sender_id();
  inline void set_allocated_sender_id(::Battlenet::EntityId* sender_id);

  // required .Battlenet.EntityId target_id = 2;
  inline bool has_target_id() const;
  inline void clear_target_id();
  static const int kTargetIdFieldNumber = 2;
  inline const ::Battlenet::EntityId& target_id() const;
  inline ::Battlenet::EntityId* mutable_target_id();
  inline ::Battlenet::EntityId* release_target_id();
  inline void set_allocated_target_id(::Battlenet::EntityId* target_id);

  // required string type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline const ::std::string& type() const;
  inline void set_type(const ::std::string& value);
  inline void set_type(const char* value);
  inline void set_type(const char* value, size_t size);
  inline ::std::string* mutable_type();
  inline ::std::string* release_type();
  inline void set_allocated_type(::std::string* type);

  // repeated .Battlenet.Attribute attribute = 4;
  inline int attribute_size() const;
  inline void clear_attribute();
  static const int kAttributeFieldNumber = 4;
  inline const ::Battlenet::Attribute& attribute(int index) const;
  inline ::Battlenet::Attribute* mutable_attribute(int index);
  inline ::Battlenet::Attribute* add_attribute();
  inline const ::google::protobuf::RepeatedPtrField< ::Battlenet::Attribute >&
      attribute() const;
  inline ::google::protobuf::RepeatedPtrField< ::Battlenet::Attribute >*
      mutable_attribute();

  // optional .Battlenet.EntityId sender_account_id = 5;
  inline bool has_sender_account_id() const;
  inline void clear_sender_account_id();
  static const int kSenderAccountIdFieldNumber = 5;
  inline const ::Battlenet::EntityId& sender_account_id() const;
  inline ::Battlenet::EntityId* mutable_sender_account_id();
  inline ::Battlenet::EntityId* release_sender_account_id();
  inline void set_allocated_sender_account_id(::Battlenet::EntityId* sender_account_id);

  // optional .Battlenet.EntityId target_account_id = 6;
  inline bool has_target_account_id() const;
  inline void clear_target_account_id();
  static const int kTargetAccountIdFieldNumber = 6;
  inline const ::Battlenet::EntityId& target_account_id() const;
  inline ::Battlenet::EntityId* mutable_target_account_id();
  inline ::Battlenet::EntityId* release_target_account_id();
  inline void set_allocated_target_account_id(::Battlenet::EntityId* target_account_id);

  // optional string sender_battle_tag = 7;
  inline bool has_sender_battle_tag() const;
  inline void clear_sender_battle_tag();
  static const int kSenderBattleTagFieldNumber = 7;
  inline const ::std::string& sender_battle_tag() const;
  inline void set_sender_battle_tag(const ::std::string& value);
  inline void set_sender_battle_tag(const char* value);
  inline void set_sender_battle_tag(const char* value, size_t size);
  inline ::std::string* mutable_sender_battle_tag();
  inline ::std::string* release_sender_battle_tag();
  inline void set_allocated_sender_battle_tag(::std::string* sender_battle_tag);

  // optional string target_battle_tag = 8;
  inline bool has_target_battle_tag() const;
  inline void clear_target_battle_tag();
  static const int kTargetBattleTagFieldNumber = 8;
  inline const ::std::string& target_battle_tag() const;
  inline void set_target_battle_tag(const ::std::string& value);
  inline void set_target_battle_tag(const char* value);
  inline void set_target_battle_tag(const char* value, size_t size);
  inline ::std::string* mutable_target_battle_tag();
  inline ::std::string* release_target_battle_tag();
  inline void set_allocated_target_battle_tag(::std::string* target_battle_tag);

  // optional .Battlenet.ProcessId peer = 9;
  inline bool has_peer() const;
  inline void clear_peer();
  static const int kPeerFieldNumber = 9;
  inline const ::Battlenet::ProcessId& peer() const;
  inline ::Battlenet::ProcessId* mutable_peer();
  inline ::Battlenet::ProcessId* release_peer();
  inline void set_allocated_peer(::Battlenet::ProcessId* peer);

  // optional .Battlenet.account.Identity forwarding_identity = 10;
  inline bool has_forwarding_identity() const;
  inline void clear_forwarding_identity();
  static const int kForwardingIdentityFieldNumber = 10;
  inline const ::Battlenet::account::Identity& forwarding_identity() const;
  inline ::Battlenet::account::Identity* mutable_forwarding_identity();
  inline ::Battlenet::account::Identity* release_forwarding_identity();
  inline void set_allocated_forwarding_identity(::Battlenet::account::Identity* forwarding_identity);

  // @@protoc_insertion_point(class_scope:Battlenet.notification.Notification)
 private:
  inline void set_has_sender_id();
  inline void clear_has_sender_id();
  inline void set_has_target_id();
  inline void clear_has_target_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_sender_account_id();
  inline void clear_has_sender_account_id();
  inline void set_has_target_account_id();
  inline void clear_has_target_account_id();
  inline void set_has_sender_battle_tag();
  inline void clear_has_sender_battle_tag();
  inline void set_has_target_battle_tag();
  inline void clear_has_target_battle_tag();
  inline void set_has_peer();
  inline void clear_has_peer();
  inline void set_has_forwarding_identity();
  inline void clear_has_forwarding_identity();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::Battlenet::EntityId* sender_id_;
  ::Battlenet::EntityId* target_id_;
  ::std::string* type_;
  ::google::protobuf::RepeatedPtrField< ::Battlenet::Attribute > attribute_;
  ::Battlenet::EntityId* sender_account_id_;
  ::Battlenet::EntityId* target_account_id_;
  ::std::string* sender_battle_tag_;
  ::std::string* target_battle_tag_;
  ::Battlenet::ProcessId* peer_;
  ::Battlenet::account::Identity* forwarding_identity_;
  friend void  protobuf_AddDesc_notification_5ftypes_2eproto();
  friend void protobuf_AssignDesc_notification_5ftypes_2eproto();
  friend void protobuf_ShutdownFile_notification_5ftypes_2eproto();

  void InitAsDefaultInstance();
  static Notification* default_instance_;
};
// ===================================================================


// ===================================================================

// Target

// optional .Battlenet.account.Identity identity = 1;
inline bool Target::has_identity() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Target::set_has_identity() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Target::clear_has_identity() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Target::clear_identity() {
  if (identity_ != NULL) identity_->::Battlenet::account::Identity::Clear();
  clear_has_identity();
}
inline const ::Battlenet::account::Identity& Target::identity() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Target.identity)
  return identity_ != NULL ? *identity_ : *default_instance_->identity_;
}
inline ::Battlenet::account::Identity* Target::mutable_identity() {
  set_has_identity();
  if (identity_ == NULL) identity_ = new ::Battlenet::account::Identity;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Target.identity)
  return identity_;
}
inline ::Battlenet::account::Identity* Target::release_identity() {
  clear_has_identity();
  ::Battlenet::account::Identity* temp = identity_;
  identity_ = NULL;
  return temp;
}
inline void Target::set_allocated_identity(::Battlenet::account::Identity* identity) {
  delete identity_;
  identity_ = identity;
  if (identity) {
    set_has_identity();
  } else {
    clear_has_identity();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Target.identity)
}

// optional string type = 2;
inline bool Target::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Target::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Target::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Target::clear_type() {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_->clear();
  }
  clear_has_type();
}
inline const ::std::string& Target::type() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Target.type)
  return *type_;
}
inline void Target::set_type(const ::std::string& value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set:Battlenet.notification.Target.type)
}
inline void Target::set_type(const char* value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set_char:Battlenet.notification.Target.type)
}
inline void Target::set_type(const char* value, size_t size) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Battlenet.notification.Target.type)
}
inline ::std::string* Target::mutable_type() {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Target.type)
  return type_;
}
inline ::std::string* Target::release_type() {
  clear_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = type_;
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Target::set_allocated_type(::std::string* type) {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete type_;
  }
  if (type) {
    set_has_type();
    type_ = type;
  } else {
    clear_has_type();
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Target.type)
}

// -------------------------------------------------------------------

// Subscription

// repeated .Battlenet.notification.Target target = 1;
inline int Subscription::target_size() const {
  return target_.size();
}
inline void Subscription::clear_target() {
  target_.Clear();
}
inline const ::Battlenet::notification::Target& Subscription::target(int index) const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Subscription.target)
  return target_.Get(index);
}
inline ::Battlenet::notification::Target* Subscription::mutable_target(int index) {
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Subscription.target)
  return target_.Mutable(index);
}
inline ::Battlenet::notification::Target* Subscription::add_target() {
  // @@protoc_insertion_point(field_add:Battlenet.notification.Subscription.target)
  return target_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Battlenet::notification::Target >&
Subscription::target() const {
  // @@protoc_insertion_point(field_list:Battlenet.notification.Subscription.target)
  return target_;
}
inline ::google::protobuf::RepeatedPtrField< ::Battlenet::notification::Target >*
Subscription::mutable_target() {
  // @@protoc_insertion_point(field_mutable_list:Battlenet.notification.Subscription.target)
  return &target_;
}

// optional .Battlenet.account.Identity subscriber = 2;
inline bool Subscription::has_subscriber() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Subscription::set_has_subscriber() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Subscription::clear_has_subscriber() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Subscription::clear_subscriber() {
  if (subscriber_ != NULL) subscriber_->::Battlenet::account::Identity::Clear();
  clear_has_subscriber();
}
inline const ::Battlenet::account::Identity& Subscription::subscriber() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Subscription.subscriber)
  return subscriber_ != NULL ? *subscriber_ : *default_instance_->subscriber_;
}
inline ::Battlenet::account::Identity* Subscription::mutable_subscriber() {
  set_has_subscriber();
  if (subscriber_ == NULL) subscriber_ = new ::Battlenet::account::Identity;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Subscription.subscriber)
  return subscriber_;
}
inline ::Battlenet::account::Identity* Subscription::release_subscriber() {
  clear_has_subscriber();
  ::Battlenet::account::Identity* temp = subscriber_;
  subscriber_ = NULL;
  return temp;
}
inline void Subscription::set_allocated_subscriber(::Battlenet::account::Identity* subscriber) {
  delete subscriber_;
  subscriber_ = subscriber;
  if (subscriber) {
    set_has_subscriber();
  } else {
    clear_has_subscriber();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Subscription.subscriber)
}

// optional bool delivery_required = 3 [default = false];
inline bool Subscription::has_delivery_required() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Subscription::set_has_delivery_required() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Subscription::clear_has_delivery_required() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Subscription::clear_delivery_required() {
  delivery_required_ = false;
  clear_has_delivery_required();
}
inline bool Subscription::delivery_required() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Subscription.delivery_required)
  return delivery_required_;
}
inline void Subscription::set_delivery_required(bool value) {
  set_has_delivery_required();
  delivery_required_ = value;
  // @@protoc_insertion_point(field_set:Battlenet.notification.Subscription.delivery_required)
}

// -------------------------------------------------------------------

// Notification

// optional .Battlenet.EntityId sender_id = 1;
inline bool Notification::has_sender_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Notification::set_has_sender_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Notification::clear_has_sender_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Notification::clear_sender_id() {
  if (sender_id_ != NULL) sender_id_->::Battlenet::EntityId::Clear();
  clear_has_sender_id();
}
inline const ::Battlenet::EntityId& Notification::sender_id() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.sender_id)
  return sender_id_ != NULL ? *sender_id_ : *default_instance_->sender_id_;
}
inline ::Battlenet::EntityId* Notification::mutable_sender_id() {
  set_has_sender_id();
  if (sender_id_ == NULL) sender_id_ = new ::Battlenet::EntityId;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.sender_id)
  return sender_id_;
}
inline ::Battlenet::EntityId* Notification::release_sender_id() {
  clear_has_sender_id();
  ::Battlenet::EntityId* temp = sender_id_;
  sender_id_ = NULL;
  return temp;
}
inline void Notification::set_allocated_sender_id(::Battlenet::EntityId* sender_id) {
  delete sender_id_;
  sender_id_ = sender_id;
  if (sender_id) {
    set_has_sender_id();
  } else {
    clear_has_sender_id();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.sender_id)
}

// required .Battlenet.EntityId target_id = 2;
inline bool Notification::has_target_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Notification::set_has_target_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Notification::clear_has_target_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Notification::clear_target_id() {
  if (target_id_ != NULL) target_id_->::Battlenet::EntityId::Clear();
  clear_has_target_id();
}
inline const ::Battlenet::EntityId& Notification::target_id() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.target_id)
  return target_id_ != NULL ? *target_id_ : *default_instance_->target_id_;
}
inline ::Battlenet::EntityId* Notification::mutable_target_id() {
  set_has_target_id();
  if (target_id_ == NULL) target_id_ = new ::Battlenet::EntityId;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.target_id)
  return target_id_;
}
inline ::Battlenet::EntityId* Notification::release_target_id() {
  clear_has_target_id();
  ::Battlenet::EntityId* temp = target_id_;
  target_id_ = NULL;
  return temp;
}
inline void Notification::set_allocated_target_id(::Battlenet::EntityId* target_id) {
  delete target_id_;
  target_id_ = target_id;
  if (target_id) {
    set_has_target_id();
  } else {
    clear_has_target_id();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.target_id)
}

// required string type = 3;
inline bool Notification::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Notification::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Notification::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Notification::clear_type() {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_->clear();
  }
  clear_has_type();
}
inline const ::std::string& Notification::type() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.type)
  return *type_;
}
inline void Notification::set_type(const ::std::string& value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set:Battlenet.notification.Notification.type)
}
inline void Notification::set_type(const char* value) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(value);
  // @@protoc_insertion_point(field_set_char:Battlenet.notification.Notification.type)
}
inline void Notification::set_type(const char* value, size_t size) {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  type_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Battlenet.notification.Notification.type)
}
inline ::std::string* Notification::mutable_type() {
  set_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    type_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.type)
  return type_;
}
inline ::std::string* Notification::release_type() {
  clear_has_type();
  if (type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = type_;
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Notification::set_allocated_type(::std::string* type) {
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete type_;
  }
  if (type) {
    set_has_type();
    type_ = type;
  } else {
    clear_has_type();
    type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.type)
}

// repeated .Battlenet.Attribute attribute = 4;
inline int Notification::attribute_size() const {
  return attribute_.size();
}
inline void Notification::clear_attribute() {
  attribute_.Clear();
}
inline const ::Battlenet::Attribute& Notification::attribute(int index) const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.attribute)
  return attribute_.Get(index);
}
inline ::Battlenet::Attribute* Notification::mutable_attribute(int index) {
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.attribute)
  return attribute_.Mutable(index);
}
inline ::Battlenet::Attribute* Notification::add_attribute() {
  // @@protoc_insertion_point(field_add:Battlenet.notification.Notification.attribute)
  return attribute_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Battlenet::Attribute >&
Notification::attribute() const {
  // @@protoc_insertion_point(field_list:Battlenet.notification.Notification.attribute)
  return attribute_;
}
inline ::google::protobuf::RepeatedPtrField< ::Battlenet::Attribute >*
Notification::mutable_attribute() {
  // @@protoc_insertion_point(field_mutable_list:Battlenet.notification.Notification.attribute)
  return &attribute_;
}

// optional .Battlenet.EntityId sender_account_id = 5;
inline bool Notification::has_sender_account_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Notification::set_has_sender_account_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Notification::clear_has_sender_account_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Notification::clear_sender_account_id() {
  if (sender_account_id_ != NULL) sender_account_id_->::Battlenet::EntityId::Clear();
  clear_has_sender_account_id();
}
inline const ::Battlenet::EntityId& Notification::sender_account_id() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.sender_account_id)
  return sender_account_id_ != NULL ? *sender_account_id_ : *default_instance_->sender_account_id_;
}
inline ::Battlenet::EntityId* Notification::mutable_sender_account_id() {
  set_has_sender_account_id();
  if (sender_account_id_ == NULL) sender_account_id_ = new ::Battlenet::EntityId;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.sender_account_id)
  return sender_account_id_;
}
inline ::Battlenet::EntityId* Notification::release_sender_account_id() {
  clear_has_sender_account_id();
  ::Battlenet::EntityId* temp = sender_account_id_;
  sender_account_id_ = NULL;
  return temp;
}
inline void Notification::set_allocated_sender_account_id(::Battlenet::EntityId* sender_account_id) {
  delete sender_account_id_;
  sender_account_id_ = sender_account_id;
  if (sender_account_id) {
    set_has_sender_account_id();
  } else {
    clear_has_sender_account_id();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.sender_account_id)
}

// optional .Battlenet.EntityId target_account_id = 6;
inline bool Notification::has_target_account_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Notification::set_has_target_account_id() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Notification::clear_has_target_account_id() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Notification::clear_target_account_id() {
  if (target_account_id_ != NULL) target_account_id_->::Battlenet::EntityId::Clear();
  clear_has_target_account_id();
}
inline const ::Battlenet::EntityId& Notification::target_account_id() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.target_account_id)
  return target_account_id_ != NULL ? *target_account_id_ : *default_instance_->target_account_id_;
}
inline ::Battlenet::EntityId* Notification::mutable_target_account_id() {
  set_has_target_account_id();
  if (target_account_id_ == NULL) target_account_id_ = new ::Battlenet::EntityId;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.target_account_id)
  return target_account_id_;
}
inline ::Battlenet::EntityId* Notification::release_target_account_id() {
  clear_has_target_account_id();
  ::Battlenet::EntityId* temp = target_account_id_;
  target_account_id_ = NULL;
  return temp;
}
inline void Notification::set_allocated_target_account_id(::Battlenet::EntityId* target_account_id) {
  delete target_account_id_;
  target_account_id_ = target_account_id;
  if (target_account_id) {
    set_has_target_account_id();
  } else {
    clear_has_target_account_id();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.target_account_id)
}

// optional string sender_battle_tag = 7;
inline bool Notification::has_sender_battle_tag() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Notification::set_has_sender_battle_tag() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Notification::clear_has_sender_battle_tag() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Notification::clear_sender_battle_tag() {
  if (sender_battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_battle_tag_->clear();
  }
  clear_has_sender_battle_tag();
}
inline const ::std::string& Notification::sender_battle_tag() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.sender_battle_tag)
  return *sender_battle_tag_;
}
inline void Notification::set_sender_battle_tag(const ::std::string& value) {
  set_has_sender_battle_tag();
  if (sender_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_battle_tag_ = new ::std::string;
  }
  sender_battle_tag_->assign(value);
  // @@protoc_insertion_point(field_set:Battlenet.notification.Notification.sender_battle_tag)
}
inline void Notification::set_sender_battle_tag(const char* value) {
  set_has_sender_battle_tag();
  if (sender_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_battle_tag_ = new ::std::string;
  }
  sender_battle_tag_->assign(value);
  // @@protoc_insertion_point(field_set_char:Battlenet.notification.Notification.sender_battle_tag)
}
inline void Notification::set_sender_battle_tag(const char* value, size_t size) {
  set_has_sender_battle_tag();
  if (sender_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_battle_tag_ = new ::std::string;
  }
  sender_battle_tag_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Battlenet.notification.Notification.sender_battle_tag)
}
inline ::std::string* Notification::mutable_sender_battle_tag() {
  set_has_sender_battle_tag();
  if (sender_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sender_battle_tag_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.sender_battle_tag)
  return sender_battle_tag_;
}
inline ::std::string* Notification::release_sender_battle_tag() {
  clear_has_sender_battle_tag();
  if (sender_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = sender_battle_tag_;
    sender_battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Notification::set_allocated_sender_battle_tag(::std::string* sender_battle_tag) {
  if (sender_battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sender_battle_tag_;
  }
  if (sender_battle_tag) {
    set_has_sender_battle_tag();
    sender_battle_tag_ = sender_battle_tag;
  } else {
    clear_has_sender_battle_tag();
    sender_battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.sender_battle_tag)
}

// optional string target_battle_tag = 8;
inline bool Notification::has_target_battle_tag() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Notification::set_has_target_battle_tag() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Notification::clear_has_target_battle_tag() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Notification::clear_target_battle_tag() {
  if (target_battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_battle_tag_->clear();
  }
  clear_has_target_battle_tag();
}
inline const ::std::string& Notification::target_battle_tag() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.target_battle_tag)
  return *target_battle_tag_;
}
inline void Notification::set_target_battle_tag(const ::std::string& value) {
  set_has_target_battle_tag();
  if (target_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_battle_tag_ = new ::std::string;
  }
  target_battle_tag_->assign(value);
  // @@protoc_insertion_point(field_set:Battlenet.notification.Notification.target_battle_tag)
}
inline void Notification::set_target_battle_tag(const char* value) {
  set_has_target_battle_tag();
  if (target_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_battle_tag_ = new ::std::string;
  }
  target_battle_tag_->assign(value);
  // @@protoc_insertion_point(field_set_char:Battlenet.notification.Notification.target_battle_tag)
}
inline void Notification::set_target_battle_tag(const char* value, size_t size) {
  set_has_target_battle_tag();
  if (target_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_battle_tag_ = new ::std::string;
  }
  target_battle_tag_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Battlenet.notification.Notification.target_battle_tag)
}
inline ::std::string* Notification::mutable_target_battle_tag() {
  set_has_target_battle_tag();
  if (target_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    target_battle_tag_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.target_battle_tag)
  return target_battle_tag_;
}
inline ::std::string* Notification::release_target_battle_tag() {
  clear_has_target_battle_tag();
  if (target_battle_tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = target_battle_tag_;
    target_battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Notification::set_allocated_target_battle_tag(::std::string* target_battle_tag) {
  if (target_battle_tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete target_battle_tag_;
  }
  if (target_battle_tag) {
    set_has_target_battle_tag();
    target_battle_tag_ = target_battle_tag;
  } else {
    clear_has_target_battle_tag();
    target_battle_tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.target_battle_tag)
}

// optional .Battlenet.ProcessId peer = 9;
inline bool Notification::has_peer() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Notification::set_has_peer() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Notification::clear_has_peer() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Notification::clear_peer() {
  if (peer_ != NULL) peer_->::Battlenet::ProcessId::Clear();
  clear_has_peer();
}
inline const ::Battlenet::ProcessId& Notification::peer() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.peer)
  return peer_ != NULL ? *peer_ : *default_instance_->peer_;
}
inline ::Battlenet::ProcessId* Notification::mutable_peer() {
  set_has_peer();
  if (peer_ == NULL) peer_ = new ::Battlenet::ProcessId;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.peer)
  return peer_;
}
inline ::Battlenet::ProcessId* Notification::release_peer() {
  clear_has_peer();
  ::Battlenet::ProcessId* temp = peer_;
  peer_ = NULL;
  return temp;
}
inline void Notification::set_allocated_peer(::Battlenet::ProcessId* peer) {
  delete peer_;
  peer_ = peer;
  if (peer) {
    set_has_peer();
  } else {
    clear_has_peer();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.peer)
}

// optional .Battlenet.account.Identity forwarding_identity = 10;
inline bool Notification::has_forwarding_identity() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Notification::set_has_forwarding_identity() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Notification::clear_has_forwarding_identity() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Notification::clear_forwarding_identity() {
  if (forwarding_identity_ != NULL) forwarding_identity_->::Battlenet::account::Identity::Clear();
  clear_has_forwarding_identity();
}
inline const ::Battlenet::account::Identity& Notification::forwarding_identity() const {
  // @@protoc_insertion_point(field_get:Battlenet.notification.Notification.forwarding_identity)
  return forwarding_identity_ != NULL ? *forwarding_identity_ : *default_instance_->forwarding_identity_;
}
inline ::Battlenet::account::Identity* Notification::mutable_forwarding_identity() {
  set_has_forwarding_identity();
  if (forwarding_identity_ == NULL) forwarding_identity_ = new ::Battlenet::account::Identity;
  // @@protoc_insertion_point(field_mutable:Battlenet.notification.Notification.forwarding_identity)
  return forwarding_identity_;
}
inline ::Battlenet::account::Identity* Notification::release_forwarding_identity() {
  clear_has_forwarding_identity();
  ::Battlenet::account::Identity* temp = forwarding_identity_;
  forwarding_identity_ = NULL;
  return temp;
}
inline void Notification::set_allocated_forwarding_identity(::Battlenet::account::Identity* forwarding_identity) {
  delete forwarding_identity_;
  forwarding_identity_ = forwarding_identity;
  if (forwarding_identity) {
    set_has_forwarding_identity();
  } else {
    clear_has_forwarding_identity();
  }
  // @@protoc_insertion_point(field_set_allocated:Battlenet.notification.Notification.forwarding_identity)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace notification
}  // namespace Battlenet

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_notification_5ftypes_2eproto__INCLUDED
