// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JSONStructures.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "JSONStructures.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Battlenet {
namespace JSON {

namespace {

const ::google::protobuf::Descriptor* FormInput_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FormInput_reflection_ = NULL;
const ::google::protobuf::Descriptor* FormInputs_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FormInputs_reflection_ = NULL;
const ::google::protobuf::Descriptor* FormInputValue_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FormInputValue_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoginForm_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginForm_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoginResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginResult_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmListTicketIdentity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmListTicketIdentity_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientVersion_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientVersion_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientInformation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientInformation_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmListTicketClientInformation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmListTicketClientInformation_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmCharacterCountEntry_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmCharacterCountEntry_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmCharacterCountList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmCharacterCountList_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmUpdate_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmUpdate_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmState_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmListUpdates_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmListUpdates_reflection_ = NULL;
const ::google::protobuf::Descriptor* IPAddress_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  IPAddress_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmIPAddressFamily_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmIPAddressFamily_reflection_ = NULL;
const ::google::protobuf::Descriptor* RealmListServerIPAddresses_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RealmListServerIPAddresses_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* FormType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* AuthenticationState_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_JSONStructures_2eproto() {
  protobuf_AddDesc_JSONStructures_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "JSONStructures.proto");
  GOOGLE_CHECK(file != NULL);
  FormInput_descriptor_ = file->message_type(0);
  static const int FormInput_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInput, input_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInput, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInput, label_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInput, max_length_),
  };
  FormInput_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FormInput_descriptor_,
      FormInput::default_instance_,
      FormInput_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInput, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInput, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FormInput));
  FormInputs_descriptor_ = file->message_type(1);
  static const int FormInputs_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputs, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputs, inputs_),
  };
  FormInputs_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FormInputs_descriptor_,
      FormInputs::default_instance_,
      FormInputs_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputs, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputs, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FormInputs));
  FormInputValue_descriptor_ = file->message_type(2);
  static const int FormInputValue_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputValue, input_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputValue, value_),
  };
  FormInputValue_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FormInputValue_descriptor_,
      FormInputValue::default_instance_,
      FormInputValue_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputValue, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormInputValue, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FormInputValue));
  LoginForm_descriptor_ = file->message_type(3);
  static const int LoginForm_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginForm, platform_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginForm, program_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginForm, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginForm, inputs_),
  };
  LoginForm_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LoginForm_descriptor_,
      LoginForm::default_instance_,
      LoginForm_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginForm, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginForm, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LoginForm));
  LoginResult_descriptor_ = file->message_type(4);
  static const int LoginResult_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResult, authentication_state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResult, error_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResult, error_message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResult, url_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResult, login_ticket_),
  };
  LoginResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LoginResult_descriptor_,
      LoginResult::default_instance_,
      LoginResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LoginResult));
  RealmListTicketIdentity_descriptor_ = file->message_type(5);
  static const int RealmListTicketIdentity_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListTicketIdentity, gameaccountid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListTicketIdentity, gameaccountregion_),
  };
  RealmListTicketIdentity_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmListTicketIdentity_descriptor_,
      RealmListTicketIdentity::default_instance_,
      RealmListTicketIdentity_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListTicketIdentity, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListTicketIdentity, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmListTicketIdentity));
  ClientVersion_descriptor_ = file->message_type(6);
  static const int ClientVersion_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientVersion, versionmajor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientVersion, versionminor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientVersion, versionrevision_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientVersion, versionbuild_),
  };
  ClientVersion_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClientVersion_descriptor_,
      ClientVersion::default_instance_,
      ClientVersion_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientVersion, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientVersion, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClientVersion));
  ClientInformation_descriptor_ = file->message_type(7);
  static const int ClientInformation_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, platform_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, buildvariant_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, timezone_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, currenttime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, textlocale_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, audiolocale_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, versiondatabuild_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, secret_),
  };
  ClientInformation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClientInformation_descriptor_,
      ClientInformation::default_instance_,
      ClientInformation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientInformation, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClientInformation));
  RealmListTicketClientInformation_descriptor_ = file->message_type(8);
  static const int RealmListTicketClientInformation_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListTicketClientInformation, info_),
  };
  RealmListTicketClientInformation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmListTicketClientInformation_descriptor_,
      RealmListTicketClientInformation::default_instance_,
      RealmListTicketClientInformation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListTicketClientInformation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListTicketClientInformation, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmListTicketClientInformation));
  RealmCharacterCountEntry_descriptor_ = file->message_type(9);
  static const int RealmCharacterCountEntry_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmCharacterCountEntry, wowrealmaddress_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmCharacterCountEntry, count_),
  };
  RealmCharacterCountEntry_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmCharacterCountEntry_descriptor_,
      RealmCharacterCountEntry::default_instance_,
      RealmCharacterCountEntry_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmCharacterCountEntry, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmCharacterCountEntry, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmCharacterCountEntry));
  RealmCharacterCountList_descriptor_ = file->message_type(10);
  static const int RealmCharacterCountList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmCharacterCountList, counts_),
  };
  RealmCharacterCountList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmCharacterCountList_descriptor_,
      RealmCharacterCountList::default_instance_,
      RealmCharacterCountList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmCharacterCountList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmCharacterCountList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmCharacterCountList));
  RealmUpdate_descriptor_ = file->message_type(11);
  static const int RealmUpdate_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, wowrealmaddress_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, cfgtimezonesid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, populationstate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, cfgcategoriesid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, cfgrealmsid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, flags_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, cfgconfigsid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, cfglanguagesid_),
  };
  RealmUpdate_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmUpdate_descriptor_,
      RealmUpdate::default_instance_,
      RealmUpdate_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmUpdate, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmUpdate));
  RealmState_descriptor_ = file->message_type(12);
  static const int RealmState_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmState, update_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmState, deleting_),
  };
  RealmState_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmState_descriptor_,
      RealmState::default_instance_,
      RealmState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmState, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmState, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmState));
  RealmListUpdates_descriptor_ = file->message_type(13);
  static const int RealmListUpdates_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListUpdates, updates_),
  };
  RealmListUpdates_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmListUpdates_descriptor_,
      RealmListUpdates::default_instance_,
      RealmListUpdates_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListUpdates, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListUpdates, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmListUpdates));
  IPAddress_descriptor_ = file->message_type(14);
  static const int IPAddress_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IPAddress, ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IPAddress, port_),
  };
  IPAddress_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      IPAddress_descriptor_,
      IPAddress::default_instance_,
      IPAddress_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IPAddress, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IPAddress, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(IPAddress));
  RealmIPAddressFamily_descriptor_ = file->message_type(15);
  static const int RealmIPAddressFamily_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmIPAddressFamily, family_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmIPAddressFamily, addresses_),
  };
  RealmIPAddressFamily_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmIPAddressFamily_descriptor_,
      RealmIPAddressFamily::default_instance_,
      RealmIPAddressFamily_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmIPAddressFamily, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmIPAddressFamily, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmIPAddressFamily));
  RealmListServerIPAddresses_descriptor_ = file->message_type(16);
  static const int RealmListServerIPAddresses_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListServerIPAddresses, families_),
  };
  RealmListServerIPAddresses_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RealmListServerIPAddresses_descriptor_,
      RealmListServerIPAddresses::default_instance_,
      RealmListServerIPAddresses_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListServerIPAddresses, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RealmListServerIPAddresses, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RealmListServerIPAddresses));
  FormType_descriptor_ = file->enum_type(0);
  AuthenticationState_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_JSONStructures_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FormInput_descriptor_, &FormInput::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FormInputs_descriptor_, &FormInputs::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FormInputValue_descriptor_, &FormInputValue::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LoginForm_descriptor_, &LoginForm::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LoginResult_descriptor_, &LoginResult::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmListTicketIdentity_descriptor_, &RealmListTicketIdentity::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClientVersion_descriptor_, &ClientVersion::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClientInformation_descriptor_, &ClientInformation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmListTicketClientInformation_descriptor_, &RealmListTicketClientInformation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmCharacterCountEntry_descriptor_, &RealmCharacterCountEntry::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmCharacterCountList_descriptor_, &RealmCharacterCountList::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmUpdate_descriptor_, &RealmUpdate::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmState_descriptor_, &RealmState::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmListUpdates_descriptor_, &RealmListUpdates::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    IPAddress_descriptor_, &IPAddress::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmIPAddressFamily_descriptor_, &RealmIPAddressFamily::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RealmListServerIPAddresses_descriptor_, &RealmListServerIPAddresses::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_JSONStructures_2eproto() {
  delete FormInput::default_instance_;
  delete FormInput_reflection_;
  delete FormInputs::default_instance_;
  delete FormInputs_reflection_;
  delete FormInputValue::default_instance_;
  delete FormInputValue_reflection_;
  delete LoginForm::default_instance_;
  delete LoginForm_reflection_;
  delete LoginResult::default_instance_;
  delete LoginResult_reflection_;
  delete RealmListTicketIdentity::default_instance_;
  delete RealmListTicketIdentity_reflection_;
  delete ClientVersion::default_instance_;
  delete ClientVersion_reflection_;
  delete ClientInformation::default_instance_;
  delete ClientInformation_reflection_;
  delete RealmListTicketClientInformation::default_instance_;
  delete RealmListTicketClientInformation_reflection_;
  delete RealmCharacterCountEntry::default_instance_;
  delete RealmCharacterCountEntry_reflection_;
  delete RealmCharacterCountList::default_instance_;
  delete RealmCharacterCountList_reflection_;
  delete RealmUpdate::default_instance_;
  delete RealmUpdate_reflection_;
  delete RealmState::default_instance_;
  delete RealmState_reflection_;
  delete RealmListUpdates::default_instance_;
  delete RealmListUpdates_reflection_;
  delete IPAddress::default_instance_;
  delete IPAddress_reflection_;
  delete RealmIPAddressFamily::default_instance_;
  delete RealmIPAddressFamily_reflection_;
  delete RealmListServerIPAddresses::default_instance_;
  delete RealmListServerIPAddresses_reflection_;
}

void protobuf_AddDesc_JSONStructures_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024JSONStructures.proto\022\016Battlenet.JSON\"N"
    "\n\tFormInput\022\020\n\010input_id\030\001 \002(\t\022\014\n\004type\030\002 "
    "\002(\t\022\r\n\005label\030\003 \002(\t\022\022\n\nmax_length\030\004 \001(\r\"_"
    "\n\nFormInputs\022&\n\004type\030\001 \002(\0162\030.Battlenet.J"
    "SON.FormType\022)\n\006inputs\030\002 \003(\0132\031.Battlenet"
    ".JSON.FormInput\"1\n\016FormInputValue\022\020\n\010inp"
    "ut_id\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"u\n\tLoginForm\022"
    "\023\n\013platform_id\030\001 \002(\t\022\022\n\nprogram_id\030\002 \002(\t"
    "\022\017\n\007version\030\003 \002(\t\022.\n\006inputs\030\004 \003(\0132\036.Batt"
    "lenet.JSON.FormInputValue\"\236\001\n\013LoginResul"
    "t\022A\n\024authentication_state\030\001 \002(\0162#.Battle"
    "net.JSON.AuthenticationState\022\022\n\nerror_co"
    "de\030\002 \001(\t\022\025\n\rerror_message\030\003 \001(\t\022\013\n\003url\030\004"
    " \001(\t\022\024\n\014login_ticket\030\005 \001(\t\"K\n\027RealmListT"
    "icketIdentity\022\025\n\rgameAccountID\030\001 \002(\007\022\031\n\021"
    "gameAccountRegion\030\002 \002(\r\"j\n\rClientVersion"
    "\022\024\n\014versionMajor\030\001 \002(\r\022\024\n\014versionMinor\030\002"
    " \002(\r\022\027\n\017versionRevision\030\003 \002(\r\022\024\n\014version"
    "Build\030\004 \002(\007\"\363\001\n\021ClientInformation\022\020\n\010pla"
    "tform\030\001 \002(\007\022\024\n\014buildVariant\030\002 \002(\t\022\014\n\004typ"
    "e\030\003 \002(\007\022\020\n\010timeZone\030\004 \002(\t\022\023\n\013currentTime"
    "\030\005 \002(\r\022\022\n\ntextLocale\030\006 \002(\007\022\023\n\013audioLocal"
    "e\030\007 \002(\007\022\030\n\020versionDataBuild\030\010 \002(\007\022.\n\007ver"
    "sion\030\t \002(\0132\035.Battlenet.JSON.ClientVersio"
    "n\022\016\n\006secret\030\n \002(\014\"S\n RealmListTicketClie"
    "ntInformation\022/\n\004info\030\001 \002(\0132!.Battlenet."
    "JSON.ClientInformation\"B\n\030RealmCharacter"
    "CountEntry\022\027\n\017wowRealmAddress\030\001 \002(\007\022\r\n\005c"
    "ount\030\002 \002(\r\"S\n\027RealmCharacterCountList\0228\n"
    "\006counts\030\001 \003(\0132(.Battlenet.JSON.RealmChar"
    "acterCountEntry\"\200\002\n\013RealmUpdate\022\027\n\017wowRe"
    "almAddress\030\001 \002(\007\022\026\n\016cfgTimezonesID\030\002 \002(\r"
    "\022\027\n\017populationState\030\003 \002(\r\022\027\n\017cfgCategori"
    "esID\030\004 \002(\r\022.\n\007version\030\005 \002(\0132\035.Battlenet."
    "JSON.ClientVersion\022\023\n\013cfgRealmsID\030\006 \002(\r\022"
    "\r\n\005flags\030\007 \002(\r\022\014\n\004name\030\010 \002(\t\022\024\n\014cfgConfi"
    "gsID\030\t \002(\r\022\026\n\016cfgLanguagesID\030\n \002(\r\"K\n\nRe"
    "almState\022+\n\006update\030\001 \001(\0132\033.Battlenet.JSO"
    "N.RealmUpdate\022\020\n\010deleting\030\002 \002(\010\"\?\n\020Realm"
    "ListUpdates\022+\n\007updates\030\001 \003(\0132\032.Battlenet"
    ".JSON.RealmState\"%\n\tIPAddress\022\n\n\002ip\030\001 \002("
    "\t\022\014\n\004port\030\002 \002(\r\"T\n\024RealmIPAddressFamily\022"
    "\016\n\006family\030\001 \002(\r\022,\n\taddresses\030\002 \003(\0132\031.Bat"
    "tlenet.JSON.IPAddress\"T\n\032RealmListServer"
    "IPAddresses\0226\n\010families\030\001 \003(\0132$.Battlene"
    "t.JSON.RealmIPAddressFamily*\032\n\010FormType\022"
    "\016\n\nLOGIN_FORM\020\001*H\n\023AuthenticationState\022\t"
    "\n\005LOGIN\020\001\022\t\n\005LEGAL\020\002\022\021\n\rAUTHENTICATOR\020\003\022"
    "\010\n\004DONE\020\004B\002H\002", 1933);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "JSONStructures.proto", &protobuf_RegisterTypes);
  FormInput::default_instance_ = new FormInput();
  FormInputs::default_instance_ = new FormInputs();
  FormInputValue::default_instance_ = new FormInputValue();
  LoginForm::default_instance_ = new LoginForm();
  LoginResult::default_instance_ = new LoginResult();
  RealmListTicketIdentity::default_instance_ = new RealmListTicketIdentity();
  ClientVersion::default_instance_ = new ClientVersion();
  ClientInformation::default_instance_ = new ClientInformation();
  RealmListTicketClientInformation::default_instance_ = new RealmListTicketClientInformation();
  RealmCharacterCountEntry::default_instance_ = new RealmCharacterCountEntry();
  RealmCharacterCountList::default_instance_ = new RealmCharacterCountList();
  RealmUpdate::default_instance_ = new RealmUpdate();
  RealmState::default_instance_ = new RealmState();
  RealmListUpdates::default_instance_ = new RealmListUpdates();
  IPAddress::default_instance_ = new IPAddress();
  RealmIPAddressFamily::default_instance_ = new RealmIPAddressFamily();
  RealmListServerIPAddresses::default_instance_ = new RealmListServerIPAddresses();
  FormInput::default_instance_->InitAsDefaultInstance();
  FormInputs::default_instance_->InitAsDefaultInstance();
  FormInputValue::default_instance_->InitAsDefaultInstance();
  LoginForm::default_instance_->InitAsDefaultInstance();
  LoginResult::default_instance_->InitAsDefaultInstance();
  RealmListTicketIdentity::default_instance_->InitAsDefaultInstance();
  ClientVersion::default_instance_->InitAsDefaultInstance();
  ClientInformation::default_instance_->InitAsDefaultInstance();
  RealmListTicketClientInformation::default_instance_->InitAsDefaultInstance();
  RealmCharacterCountEntry::default_instance_->InitAsDefaultInstance();
  RealmCharacterCountList::default_instance_->InitAsDefaultInstance();
  RealmUpdate::default_instance_->InitAsDefaultInstance();
  RealmState::default_instance_->InitAsDefaultInstance();
  RealmListUpdates::default_instance_->InitAsDefaultInstance();
  IPAddress::default_instance_->InitAsDefaultInstance();
  RealmIPAddressFamily::default_instance_->InitAsDefaultInstance();
  RealmListServerIPAddresses::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_JSONStructures_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_JSONStructures_2eproto {
  StaticDescriptorInitializer_JSONStructures_2eproto() {
    protobuf_AddDesc_JSONStructures_2eproto();
  }
} static_descriptor_initializer_JSONStructures_2eproto_;
const ::google::protobuf::EnumDescriptor* FormType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FormType_descriptor_;
}
bool FormType_IsValid(int value) {
  switch(value) {
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* AuthenticationState_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AuthenticationState_descriptor_;
}
bool AuthenticationState_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int FormInput::kInputIdFieldNumber;
const int FormInput::kTypeFieldNumber;
const int FormInput::kLabelFieldNumber;
const int FormInput::kMaxLengthFieldNumber;
#endif  // !_MSC_VER

FormInput::FormInput()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.FormInput)
}

void FormInput::InitAsDefaultInstance() {
}

FormInput::FormInput(const FormInput& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.FormInput)
}

void FormInput::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  input_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  label_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  max_length_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FormInput::~FormInput() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.FormInput)
  SharedDtor();
}

void FormInput::SharedDtor() {
  if (input_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete input_id_;
  }
  if (type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete type_;
  }
  if (label_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete label_;
  }
  if (this != default_instance_) {
  }
}

void FormInput::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FormInput::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FormInput_descriptor_;
}

const FormInput& FormInput::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

FormInput* FormInput::default_instance_ = NULL;

FormInput* FormInput::New() const {
  return new FormInput;
}

void FormInput::Swap(FormInput* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata FormInput::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FormInput_descriptor_;
  metadata.reflection = FormInput_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int FormInputs::kTypeFieldNumber;
const int FormInputs::kInputsFieldNumber;
#endif  // !_MSC_VER

FormInputs::FormInputs()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.FormInputs)
}

void FormInputs::InitAsDefaultInstance() {
}

FormInputs::FormInputs(const FormInputs& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.FormInputs)
}

void FormInputs::SharedCtor() {
  _cached_size_ = 0;
  type_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FormInputs::~FormInputs() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.FormInputs)
  SharedDtor();
}

void FormInputs::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FormInputs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FormInputs::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FormInputs_descriptor_;
}

const FormInputs& FormInputs::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

FormInputs* FormInputs::default_instance_ = NULL;

FormInputs* FormInputs::New() const {
  return new FormInputs;
}

void FormInputs::Swap(FormInputs* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata FormInputs::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FormInputs_descriptor_;
  metadata.reflection = FormInputs_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int FormInputValue::kInputIdFieldNumber;
const int FormInputValue::kValueFieldNumber;
#endif  // !_MSC_VER

FormInputValue::FormInputValue()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.FormInputValue)
}

void FormInputValue::InitAsDefaultInstance() {
}

FormInputValue::FormInputValue(const FormInputValue& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.FormInputValue)
}

void FormInputValue::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  input_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FormInputValue::~FormInputValue() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.FormInputValue)
  SharedDtor();
}

void FormInputValue::SharedDtor() {
  if (input_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete input_id_;
  }
  if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

void FormInputValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FormInputValue::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FormInputValue_descriptor_;
}

const FormInputValue& FormInputValue::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

FormInputValue* FormInputValue::default_instance_ = NULL;

FormInputValue* FormInputValue::New() const {
  return new FormInputValue;
}

void FormInputValue::Swap(FormInputValue* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata FormInputValue::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FormInputValue_descriptor_;
  metadata.reflection = FormInputValue_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int LoginForm::kPlatformIdFieldNumber;
const int LoginForm::kProgramIdFieldNumber;
const int LoginForm::kVersionFieldNumber;
const int LoginForm::kInputsFieldNumber;
#endif  // !_MSC_VER

LoginForm::LoginForm()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.LoginForm)
}

void LoginForm::InitAsDefaultInstance() {
}

LoginForm::LoginForm(const LoginForm& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.LoginForm)
}

void LoginForm::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  platform_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  program_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LoginForm::~LoginForm() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.LoginForm)
  SharedDtor();
}

void LoginForm::SharedDtor() {
  if (platform_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete platform_id_;
  }
  if (program_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete program_id_;
  }
  if (version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete version_;
  }
  if (this != default_instance_) {
  }
}

void LoginForm::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginForm::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginForm_descriptor_;
}

const LoginForm& LoginForm::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

LoginForm* LoginForm::default_instance_ = NULL;

LoginForm* LoginForm::New() const {
  return new LoginForm;
}

void LoginForm::Swap(LoginForm* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata LoginForm::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginForm_descriptor_;
  metadata.reflection = LoginForm_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int LoginResult::kAuthenticationStateFieldNumber;
const int LoginResult::kErrorCodeFieldNumber;
const int LoginResult::kErrorMessageFieldNumber;
const int LoginResult::kUrlFieldNumber;
const int LoginResult::kLoginTicketFieldNumber;
#endif  // !_MSC_VER

LoginResult::LoginResult()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.LoginResult)
}

void LoginResult::InitAsDefaultInstance() {
}

LoginResult::LoginResult(const LoginResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.LoginResult)
}

void LoginResult::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  authentication_state_ = 1;
  error_code_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  url_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  login_ticket_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LoginResult::~LoginResult() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.LoginResult)
  SharedDtor();
}

void LoginResult::SharedDtor() {
  if (error_code_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_code_;
  }
  if (error_message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_message_;
  }
  if (url_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete url_;
  }
  if (login_ticket_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete login_ticket_;
  }
  if (this != default_instance_) {
  }
}

void LoginResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginResult_descriptor_;
}

const LoginResult& LoginResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

LoginResult* LoginResult::default_instance_ = NULL;

LoginResult* LoginResult::New() const {
  return new LoginResult;
}

void LoginResult::Swap(LoginResult* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata LoginResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginResult_descriptor_;
  metadata.reflection = LoginResult_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmListTicketIdentity::kGameAccountIDFieldNumber;
const int RealmListTicketIdentity::kGameAccountRegionFieldNumber;
#endif  // !_MSC_VER

RealmListTicketIdentity::RealmListTicketIdentity()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmListTicketIdentity)
}

void RealmListTicketIdentity::InitAsDefaultInstance() {
}

RealmListTicketIdentity::RealmListTicketIdentity(const RealmListTicketIdentity& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmListTicketIdentity)
}

void RealmListTicketIdentity::SharedCtor() {
  _cached_size_ = 0;
  gameaccountid_ = 0u;
  gameaccountregion_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmListTicketIdentity::~RealmListTicketIdentity() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmListTicketIdentity)
  SharedDtor();
}

void RealmListTicketIdentity::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RealmListTicketIdentity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmListTicketIdentity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmListTicketIdentity_descriptor_;
}

const RealmListTicketIdentity& RealmListTicketIdentity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmListTicketIdentity* RealmListTicketIdentity::default_instance_ = NULL;

RealmListTicketIdentity* RealmListTicketIdentity::New() const {
  return new RealmListTicketIdentity;
}

void RealmListTicketIdentity::Swap(RealmListTicketIdentity* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmListTicketIdentity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmListTicketIdentity_descriptor_;
  metadata.reflection = RealmListTicketIdentity_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ClientVersion::kVersionMajorFieldNumber;
const int ClientVersion::kVersionMinorFieldNumber;
const int ClientVersion::kVersionRevisionFieldNumber;
const int ClientVersion::kVersionBuildFieldNumber;
#endif  // !_MSC_VER

ClientVersion::ClientVersion()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.ClientVersion)
}

void ClientVersion::InitAsDefaultInstance() {
}

ClientVersion::ClientVersion(const ClientVersion& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.ClientVersion)
}

void ClientVersion::SharedCtor() {
  _cached_size_ = 0;
  versionmajor_ = 0u;
  versionminor_ = 0u;
  versionrevision_ = 0u;
  versionbuild_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientVersion::~ClientVersion() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.ClientVersion)
  SharedDtor();
}

void ClientVersion::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ClientVersion::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientVersion::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientVersion_descriptor_;
}

const ClientVersion& ClientVersion::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

ClientVersion* ClientVersion::default_instance_ = NULL;

ClientVersion* ClientVersion::New() const {
  return new ClientVersion;
}

void ClientVersion::Swap(ClientVersion* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata ClientVersion::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientVersion_descriptor_;
  metadata.reflection = ClientVersion_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ClientInformation::kPlatformFieldNumber;
const int ClientInformation::kBuildVariantFieldNumber;
const int ClientInformation::kTypeFieldNumber;
const int ClientInformation::kTimeZoneFieldNumber;
const int ClientInformation::kCurrentTimeFieldNumber;
const int ClientInformation::kTextLocaleFieldNumber;
const int ClientInformation::kAudioLocaleFieldNumber;
const int ClientInformation::kVersionDataBuildFieldNumber;
const int ClientInformation::kVersionFieldNumber;
const int ClientInformation::kSecretFieldNumber;
#endif  // !_MSC_VER

ClientInformation::ClientInformation()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.ClientInformation)
}

void ClientInformation::InitAsDefaultInstance() {
  version_ = const_cast< ::Battlenet::JSON::ClientVersion*>(&::Battlenet::JSON::ClientVersion::default_instance());
}

ClientInformation::ClientInformation(const ClientInformation& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.ClientInformation)
}

void ClientInformation::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  platform_ = 0u;
  buildvariant_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 0u;
  timezone_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  currenttime_ = 0u;
  textlocale_ = 0u;
  audiolocale_ = 0u;
  versiondatabuild_ = 0u;
  version_ = NULL;
  secret_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientInformation::~ClientInformation() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.ClientInformation)
  SharedDtor();
}

void ClientInformation::SharedDtor() {
  if (buildvariant_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete buildvariant_;
  }
  if (timezone_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete timezone_;
  }
  if (secret_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete secret_;
  }
  if (this != default_instance_) {
    delete version_;
  }
}

void ClientInformation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientInformation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientInformation_descriptor_;
}

const ClientInformation& ClientInformation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

ClientInformation* ClientInformation::default_instance_ = NULL;

ClientInformation* ClientInformation::New() const {
  return new ClientInformation;
}

void ClientInformation::Swap(ClientInformation* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata ClientInformation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientInformation_descriptor_;
  metadata.reflection = ClientInformation_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmListTicketClientInformation::kInfoFieldNumber;
#endif  // !_MSC_VER

RealmListTicketClientInformation::RealmListTicketClientInformation()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmListTicketClientInformation)
}

void RealmListTicketClientInformation::InitAsDefaultInstance() {
  info_ = const_cast< ::Battlenet::JSON::ClientInformation*>(&::Battlenet::JSON::ClientInformation::default_instance());
}

RealmListTicketClientInformation::RealmListTicketClientInformation(const RealmListTicketClientInformation& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmListTicketClientInformation)
}

void RealmListTicketClientInformation::SharedCtor() {
  _cached_size_ = 0;
  info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmListTicketClientInformation::~RealmListTicketClientInformation() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmListTicketClientInformation)
  SharedDtor();
}

void RealmListTicketClientInformation::SharedDtor() {
  if (this != default_instance_) {
    delete info_;
  }
}

void RealmListTicketClientInformation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmListTicketClientInformation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmListTicketClientInformation_descriptor_;
}

const RealmListTicketClientInformation& RealmListTicketClientInformation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmListTicketClientInformation* RealmListTicketClientInformation::default_instance_ = NULL;

RealmListTicketClientInformation* RealmListTicketClientInformation::New() const {
  return new RealmListTicketClientInformation;
}

void RealmListTicketClientInformation::Swap(RealmListTicketClientInformation* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmListTicketClientInformation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmListTicketClientInformation_descriptor_;
  metadata.reflection = RealmListTicketClientInformation_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmCharacterCountEntry::kWowRealmAddressFieldNumber;
const int RealmCharacterCountEntry::kCountFieldNumber;
#endif  // !_MSC_VER

RealmCharacterCountEntry::RealmCharacterCountEntry()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmCharacterCountEntry)
}

void RealmCharacterCountEntry::InitAsDefaultInstance() {
}

RealmCharacterCountEntry::RealmCharacterCountEntry(const RealmCharacterCountEntry& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmCharacterCountEntry)
}

void RealmCharacterCountEntry::SharedCtor() {
  _cached_size_ = 0;
  wowrealmaddress_ = 0u;
  count_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmCharacterCountEntry::~RealmCharacterCountEntry() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmCharacterCountEntry)
  SharedDtor();
}

void RealmCharacterCountEntry::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RealmCharacterCountEntry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmCharacterCountEntry::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmCharacterCountEntry_descriptor_;
}

const RealmCharacterCountEntry& RealmCharacterCountEntry::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmCharacterCountEntry* RealmCharacterCountEntry::default_instance_ = NULL;

RealmCharacterCountEntry* RealmCharacterCountEntry::New() const {
  return new RealmCharacterCountEntry;
}

void RealmCharacterCountEntry::Swap(RealmCharacterCountEntry* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmCharacterCountEntry::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmCharacterCountEntry_descriptor_;
  metadata.reflection = RealmCharacterCountEntry_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmCharacterCountList::kCountsFieldNumber;
#endif  // !_MSC_VER

RealmCharacterCountList::RealmCharacterCountList()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmCharacterCountList)
}

void RealmCharacterCountList::InitAsDefaultInstance() {
}

RealmCharacterCountList::RealmCharacterCountList(const RealmCharacterCountList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmCharacterCountList)
}

void RealmCharacterCountList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmCharacterCountList::~RealmCharacterCountList() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmCharacterCountList)
  SharedDtor();
}

void RealmCharacterCountList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RealmCharacterCountList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmCharacterCountList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmCharacterCountList_descriptor_;
}

const RealmCharacterCountList& RealmCharacterCountList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmCharacterCountList* RealmCharacterCountList::default_instance_ = NULL;

RealmCharacterCountList* RealmCharacterCountList::New() const {
  return new RealmCharacterCountList;
}

void RealmCharacterCountList::Swap(RealmCharacterCountList* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmCharacterCountList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmCharacterCountList_descriptor_;
  metadata.reflection = RealmCharacterCountList_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmUpdate::kWowRealmAddressFieldNumber;
const int RealmUpdate::kCfgTimezonesIDFieldNumber;
const int RealmUpdate::kPopulationStateFieldNumber;
const int RealmUpdate::kCfgCategoriesIDFieldNumber;
const int RealmUpdate::kVersionFieldNumber;
const int RealmUpdate::kCfgRealmsIDFieldNumber;
const int RealmUpdate::kFlagsFieldNumber;
const int RealmUpdate::kNameFieldNumber;
const int RealmUpdate::kCfgConfigsIDFieldNumber;
const int RealmUpdate::kCfgLanguagesIDFieldNumber;
#endif  // !_MSC_VER

RealmUpdate::RealmUpdate()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmUpdate)
}

void RealmUpdate::InitAsDefaultInstance() {
  version_ = const_cast< ::Battlenet::JSON::ClientVersion*>(&::Battlenet::JSON::ClientVersion::default_instance());
}

RealmUpdate::RealmUpdate(const RealmUpdate& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmUpdate)
}

void RealmUpdate::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  wowrealmaddress_ = 0u;
  cfgtimezonesid_ = 0u;
  populationstate_ = 0u;
  cfgcategoriesid_ = 0u;
  version_ = NULL;
  cfgrealmsid_ = 0u;
  flags_ = 0u;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cfgconfigsid_ = 0u;
  cfglanguagesid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmUpdate::~RealmUpdate() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmUpdate)
  SharedDtor();
}

void RealmUpdate::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
    delete version_;
  }
}

void RealmUpdate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmUpdate::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmUpdate_descriptor_;
}

const RealmUpdate& RealmUpdate::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmUpdate* RealmUpdate::default_instance_ = NULL;

RealmUpdate* RealmUpdate::New() const {
  return new RealmUpdate;
}

void RealmUpdate::Swap(RealmUpdate* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmUpdate::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmUpdate_descriptor_;
  metadata.reflection = RealmUpdate_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmState::kUpdateFieldNumber;
const int RealmState::kDeletingFieldNumber;
#endif  // !_MSC_VER

RealmState::RealmState()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmState)
}

void RealmState::InitAsDefaultInstance() {
  update_ = const_cast< ::Battlenet::JSON::RealmUpdate*>(&::Battlenet::JSON::RealmUpdate::default_instance());
}

RealmState::RealmState(const RealmState& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmState)
}

void RealmState::SharedCtor() {
  _cached_size_ = 0;
  update_ = NULL;
  deleting_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmState::~RealmState() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmState)
  SharedDtor();
}

void RealmState::SharedDtor() {
  if (this != default_instance_) {
    delete update_;
  }
}

void RealmState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmState_descriptor_;
}

const RealmState& RealmState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmState* RealmState::default_instance_ = NULL;

RealmState* RealmState::New() const {
  return new RealmState;
}

void RealmState::Swap(RealmState* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmState_descriptor_;
  metadata.reflection = RealmState_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmListUpdates::kUpdatesFieldNumber;
#endif  // !_MSC_VER

RealmListUpdates::RealmListUpdates()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmListUpdates)
}

void RealmListUpdates::InitAsDefaultInstance() {
}

RealmListUpdates::RealmListUpdates(const RealmListUpdates& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmListUpdates)
}

void RealmListUpdates::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmListUpdates::~RealmListUpdates() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmListUpdates)
  SharedDtor();
}

void RealmListUpdates::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RealmListUpdates::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmListUpdates::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmListUpdates_descriptor_;
}

const RealmListUpdates& RealmListUpdates::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmListUpdates* RealmListUpdates::default_instance_ = NULL;

RealmListUpdates* RealmListUpdates::New() const {
  return new RealmListUpdates;
}

void RealmListUpdates::Swap(RealmListUpdates* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmListUpdates::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmListUpdates_descriptor_;
  metadata.reflection = RealmListUpdates_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int IPAddress::kIpFieldNumber;
const int IPAddress::kPortFieldNumber;
#endif  // !_MSC_VER

IPAddress::IPAddress()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.IPAddress)
}

void IPAddress::InitAsDefaultInstance() {
}

IPAddress::IPAddress(const IPAddress& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.IPAddress)
}

void IPAddress::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

IPAddress::~IPAddress() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.IPAddress)
  SharedDtor();
}

void IPAddress::SharedDtor() {
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ip_;
  }
  if (this != default_instance_) {
  }
}

void IPAddress::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* IPAddress::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return IPAddress_descriptor_;
}

const IPAddress& IPAddress::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

IPAddress* IPAddress::default_instance_ = NULL;

IPAddress* IPAddress::New() const {
  return new IPAddress;
}

void IPAddress::Swap(IPAddress* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata IPAddress::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = IPAddress_descriptor_;
  metadata.reflection = IPAddress_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmIPAddressFamily::kFamilyFieldNumber;
const int RealmIPAddressFamily::kAddressesFieldNumber;
#endif  // !_MSC_VER

RealmIPAddressFamily::RealmIPAddressFamily()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmIPAddressFamily)
}

void RealmIPAddressFamily::InitAsDefaultInstance() {
}

RealmIPAddressFamily::RealmIPAddressFamily(const RealmIPAddressFamily& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmIPAddressFamily)
}

void RealmIPAddressFamily::SharedCtor() {
  _cached_size_ = 0;
  family_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmIPAddressFamily::~RealmIPAddressFamily() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmIPAddressFamily)
  SharedDtor();
}

void RealmIPAddressFamily::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RealmIPAddressFamily::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmIPAddressFamily::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmIPAddressFamily_descriptor_;
}

const RealmIPAddressFamily& RealmIPAddressFamily::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmIPAddressFamily* RealmIPAddressFamily::default_instance_ = NULL;

RealmIPAddressFamily* RealmIPAddressFamily::New() const {
  return new RealmIPAddressFamily;
}

void RealmIPAddressFamily::Swap(RealmIPAddressFamily* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmIPAddressFamily::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmIPAddressFamily_descriptor_;
  metadata.reflection = RealmIPAddressFamily_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RealmListServerIPAddresses::kFamiliesFieldNumber;
#endif  // !_MSC_VER

RealmListServerIPAddresses::RealmListServerIPAddresses()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Battlenet.JSON.RealmListServerIPAddresses)
}

void RealmListServerIPAddresses::InitAsDefaultInstance() {
}

RealmListServerIPAddresses::RealmListServerIPAddresses(const RealmListServerIPAddresses& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Battlenet.JSON.RealmListServerIPAddresses)
}

void RealmListServerIPAddresses::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RealmListServerIPAddresses::~RealmListServerIPAddresses() {
  // @@protoc_insertion_point(destructor:Battlenet.JSON.RealmListServerIPAddresses)
  SharedDtor();
}

void RealmListServerIPAddresses::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RealmListServerIPAddresses::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RealmListServerIPAddresses::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RealmListServerIPAddresses_descriptor_;
}

const RealmListServerIPAddresses& RealmListServerIPAddresses::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_JSONStructures_2eproto();
  return *default_instance_;
}

RealmListServerIPAddresses* RealmListServerIPAddresses::default_instance_ = NULL;

RealmListServerIPAddresses* RealmListServerIPAddresses::New() const {
  return new RealmListServerIPAddresses;
}

void RealmListServerIPAddresses::Swap(RealmListServerIPAddresses* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata RealmListServerIPAddresses::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RealmListServerIPAddresses_descriptor_;
  metadata.reflection = RealmListServerIPAddresses_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace JSON
}  // namespace Battlenet

// @@protoc_insertion_point(global_scope)
